### ISSUE TITLE
Place back the Jitsi logo

### ISSUE THREAD

**Issue by lenny-horstink** [cortezaproject/corteza-webapp-unify#32]
The Jitsi logo needs to be placed back in the iframe. See: https://twitter.com/jitsinews/status/1147103379165986816

In the link Jitsi passed on to us (https://github.com/jitsi/jitsi-meet/blob/master/doc/api.md#jitsi-meet-api)

> You can use the Jitsi Meet API to embed Jitsi Meet in to your application. You are also welcome to use it for embedding the globally distributed and highly available deployment on meet.jit.si itself. The only thing we ask for in that case is that you please DO NOT remove the jitsi.org logo from the top left corner.

**Comment by tjerman** [comment]
Resolved in 0a113c35239546964b2113074d573a1124f65b90.
![Screenshot from 2019-07-08 22-12-55](https://user-images.githubusercontent.com/12545711/60839511-a16aa800-a1cd-11e9-8204-ce0d9deb8e1e.png)
